from enum import Enum


class ClearingReportTypeEnum(Enum):
    TRANSACTIONS = 1
    POSITIONS = 2
    ACCMVALUE = 3
    DELIVERY = 4
    FUTMTM = 5
    NONPROPMRGINTRA = 6
    COLLATVALUE = 7
    CASHOPTIMIZATION = 8
    SPAN_PARAM_FILEHEADERLIST = 9
    SPAN_PARAM_RISKGROUPLIST = 10
    SPAN_PARAM_CONTRACTINFOLIST = 11
    SPAN_PARAM_RISKARRAYSLIST = 12
    SPAN_PARAM_CORRELATIONLIST = 13
    SPAN_PARAM_TIMESPREADLIST = 14
    SPAN_PARAM_CURRENCYCONVERSIONLIST = 15
    SPAN_PARAM_RNPDEFINITIONSLIST = 16
    SPAN_PARAM_RNPELEMENTSLIST = 17
    SPAN_PARAM_INTERCOMMODITYSPREADCREDITSLIST = 18
    SPAN_PARAM_DELIVERYCALENDARDATALIST = 19
    SPAN_PARAM_NONDELIVERYDATESLIST = 20
    SPAN_PARAM_TIMEPERIODLIST = 21
    SPAN_PARAM_TRAILERLIST = 22


